### ISSUE TITLE
The program doesn't download videos, and throws an exception

### ISSUE THREAD

**Issue by a2ys** [prateekralhan/Python-based-Youtube-downloader#2]
Whenever I try to download a video, say this one [Morbius Trailer](https://www.youtube.com/watch?v=oZ6iiRrz1SY), it throws the following error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Downloads\new\Python-based-Youtube-downloader\python_youtube_downloader.py", line 12, in entry_fields
    YouTube(e1.get()).streams.first().download(download_location)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W
```
I can't find any solution for it, hope you can help!

**Comment by a2ys** [comment]
Sorry to bother but I found a solution myself. It is a bug from the library itself. You need to follow the following steps:
1. First go to C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python310\Lib\site-packages\pytube on Windows or `pip find pytube` and go to the location on Linux or Mac.
2. Open the file `cipher.py` and edit `Line 30` as:
```
var_regex = re.compile(r"^\$*\w+\W")
```

Now there will be no issues!

**Comment by Akhil928** [comment]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pytube in c:\users\akhil\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages `(15.0.0)```

IT WAS SHOWING LIKE THIS I HOPE U CAN HELP WITH THIS I'M  NOT GETTING RUN THE CODE

**Comment by prateekralhan** [comment]
You seem to have Python 3.12 in your system and pytube ( underlying dependency for this app ) doesn't support Python 3.12. See [this](https://github.com/pytube/pytube/blob/master/setup.py)
